### ISSUE TITLE
Cannot find module 'crel'

### ISSUE THREAD

**Issue by shotlom** [KoryNunn/fastn#27]
```
Error: Cannot find module 'crel' from '/home/adminuser/Dev/fatsn-test/node_modules/fastn'
    at /home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/adminuser/Dev/fatsn-test/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by KoryNunn** [comment]
My bad, I thought there was no hard dep on crel so I removed it from the package.json. toComponent still uses it. I may remove the dependency at some stage, but it's fine for now.

**Comment by shotlom** [comment]
Shouldn't the production deployment tests pick this up rather than users?

**Comment by KoryNunn** [comment]
Crel is a dev dep, so running it standalone means it is always installed. Might need to make a new test proj..
